# Generated by Django 2.1.7 on 2019-03-20 04:14

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):


    operations = [
        migrations.CreateModel(
            name='HomestaySimilarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_homestay_id', models.IntegerField(default=0)),
                ('second_homestay_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
        )
    ]
